spring:
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/mfy
    username: postgres
    password: itsasecret
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        default_batch_fetch_size: 10

        cache:
          use_second_level_cache: true
          use_query_cache: false
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider

  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: miycxsglưcklcmvt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8000
  url: http://localhost:8000
  config:
    email-verification:
      required: false # account verification is required
      html: false # html template is used

client:
  url: http://localhost:3000

security:
  jwt:
    secret: "securepasswordsuchasecurepasswordsuchassecurepassword"
  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
    allowed-headers: "*"

google:
  client-id: 636869674664-bsvb57clkahahs3javmbgjzz1aez67p8.apps.googleusercontent.com
  client-secret: GODSVX-_KQplMq5QCbcSbufSX87pOYAMef3
  redirect-uri: http://localhost:8000/api/v1/auth/google/callback

# s3
cloud:
  aws:
    credentials:
      access-key: TVIA47CRXJXGT53RLF66
      secret-key: AGqZJ3/VFQoWJs5VansETYSiNMoxTu6OzuJXyGcC
    region:
      static: us-east-1
    bucket:
      public: m4y-public
      private: m4y-private

# logs
logging:
  level:
    root: INFO
  file:
    name: logs/app.log
